import datetime
import copy
saverdata = {  
   "home_team":"Corinthians",
   "home_logo_src":"http://i.sportstats.com/EJjZAohQ-4GpinQcR.png",
   "time":datetime.time(0, 0),
   "away_logo_src":"http://i.sportstats.com/ObzPomjQ-S2oksqYj.png",
   "away_first_half_goals":0,
   "away_match_goals":0,
   "league":"Campeonato Paulista",
   "home_first_half_goals":2,
   "country":"Brazil",
   "away_team":"Bragantino",
   "date":datetime.date(2018, 3, 23),
   "home_match_goals":2,
   "away_second_half_goals":0,
   "home_second_half_goals":0
}
saverdatadeformed = {  
   "home_team":"Corinthians",
   "home_logo_src":"http://i.sportstats.com/EJjZAohQ-4GpinQcR.png",
   "time":datetime.time(0, 0),
   "away_logo_src":"http://i.sportstats.com/ObzPomjQ-S2oksqYj.png",
   "away_first_half_goals":0,
   "away_match_goals":0,
   "league":"Campeonato Paulista",
   "home_first_half_goals":2,
   "country":"Brazil",
   "away_team":"Bragantino",
   "home_match_goals":2,
   "away_second_half_goals":0,
   "home_second_half_goals":0
}
saverdatadeformed1 = {  
   "home_team":"Corinthians",
   "home_logo_src":"http://i.sportstats.com/EJjZAohQ-4GpinQcR.png",
   "time":datetime.time(0, 0),
   "away_logo_src":"http://i.sportstats.com/ObzPomjQ-S2oksqYj.png",
   "away_first_half_goals":0,
   "away_match_goals":0,
   "league":"Campeonato Paulista",
   "home_first_half_goals":2,
   "away_team":"Bragantino",
   "date":datetime.date(2018, 3, 23),
   "home_match_goals":2,
   "away_second_half_goals":0,
   "home_second_half_goals":0
}
saverdatadeformed2 = {  
   "home_team":"Corinthians",
   "home_logo_src":"http://i.sportstats.com/EJjZAohQ-4GpinQcR.png",
   "time":datetime.time(0, 0),
   "away_logo_src":"http://i.sportstats.com/ObzPomjQ-S2oksqYj.png",
   "away_first_half_goals":0,
   "away_match_goals":0,
   "home_first_half_goals":2,
   "country":"Brazil",
   "away_team":"Bragantino",
   "date":datetime.date(2018, 3, 23),
   "home_match_goals":2,
   "away_second_half_goals":0,
   "home_second_half_goals":0
}
saverdatacountry= {  
   'away_first_half_goals':1,
   'home_team':'Boca Unidos',
   'time':datetime.time(0, 0),
   'away_team':'Club Atletico Mitre',
   'home_first_half_goals':0,
   'country':'Brazil',
   'home_match_goals':1,
   'away_logo_src':'http://i.sportstats.com/fkdoMcoh-OSNzaEMG.png',
   'away_second_half_goals':1,
   'away_match_goals':2,
   'home_logo_src':'http://i.sportstats.com/IRUMW9WE-Sl6NCk6r.png',
   'home_second_half_goals':1,
   'league':'Primera B Nacional',
   'date':datetime.date(2018, 3, 26)
}
saverdataleague= {  
   'away_first_half_goals':1,
   'home_team':'Boca Unidos',
   'time':datetime.time(0, 0),
   'away_team':'Club Atletico Mitre',
   'home_first_half_goals':0,
   'country':'Argentina',
   'home_match_goals':1,
   'away_logo_src':'http://i.sportstats.com/fkdoMcoh-OSNzaEMG.png',
   'away_second_half_goals':1,
   'away_match_goals':2,
   'home_logo_src':'http://i.sportstats.com/IRUMW9WE-Sl6NCk6r.png',
   'home_second_half_goals':1,
   "league":"Campeonato Paulista",
   'date':datetime.date(2018, 3, 26)
}
save = copy.deepcopy(saverdata)
saveflagged = {  
   'away_first_half_goals':None,
   'home_team':'Portugal',
   'time':datetime.time(20, 30),
   'away_team':'Netherlands',
   'home_first_half_goals':None,
   'country':'World',
   'home_match_goals':None,
   'away_logo_src':'http://i.sportstats.com/hM4ITqUE-hfYFp0jk.png',
   'away_second_half_goals':None,
   'away_match_goals':None,
   'home_logo_src':'http://i.sportstats.com/nFK0QOCK-OS1AyatK.png',
   'home_second_half_goals':None,
   'league':'Friendly International',
   'date':datetime.date(2018, 3, 26)
}
ancestralpageplacebo1 = {
    'home_match_goals': 1,
    'home_logo_src': 'http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png',
    'away_match_goals': 2,
    'home_second_half_goals': None,
    'league': 'OFB Cup',
    'away_team': 'Kapfenberg',
    'date': datetime.date(2010, 9, 13),
    'home_team': 'FAC Wien',
    'home_first_half_goals': None,
    'away_first_half_goals': None,
    'away_second_half_goals': None,
    'country':'Austria',
    'away_logo_src':'http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png',
    'time':datetime.time(20, 0)
}

#placebo2 will hold a mutual match that holds the same league but without any prefix or suffix
ancestralpageplacebo2 = {
        "away_team":"Neustadt",
        "away_second_half_goals":0,
        "away_match_goals":3,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":3,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/A7qnAnUE-MsnoecZK.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        9        ),
        "country":"Austria"
    }
ancestralpage = {
    'home_match_goals': 1,
    'home_logo_src': 'http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png',
    'away_match_goals': 2,
    'home_second_half_goals': None,
    'league': 'OFB Cup',
    'away_team': 'Kapfenberg',
    'date': datetime.date(2010, 8, 13),
    'home_team': 'FAC Wien',
    'home_first_half_goals': None,
    'away_first_half_goals': None,
    'away_second_half_goals': None,
    'country':'Austria',
    'away_logo_src':'http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png',
    'time':datetime.time(20, 0)
}  # for the tango test

########################################################################################################################

diction_list = [
    {
        "away_team":"Neustadt",
        "away_second_half_goals":0,
        "away_match_goals":3,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":3,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/A7qnAnUE-MsnoecZK.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        9        ),
        "country":"Austria"
    },
    {
        "away_team":"A. Lustenau",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":1,
        "home_match_goals":2,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/hnDiE7oh-hUxALml3.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        24        ),
        "country":"Austria"
    },
    {
        "away_team":"BW Linz",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/IyIb4H7n-CWnHJbm6.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        3        ),
        "country":"Austria"
    },
    {
        "away_team":"Liefering",
        "away_second_half_goals":2,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":2,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/6o19JD9K-O0THtLIa.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        10,
        20        ),
        "country":"Austria"
    },
    {
        "away_team":"Ried",
        "away_second_half_goals":3,
        "away_match_goals":4,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":1,
        "home_second_half_goals":1,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/2qC9lyTc-EZyzCyg4.png",
        "time":datetime.time(20,
        30        ),
        "date":datetime.date(2017,
        9,
        22        ),
        "country":"Austria"
    },
    {
        "away_team":"Hartberg",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":2,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/4AytPeA3-vLZTsIYf.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        9,
        15        ),
        "country":"Austria"
    },
    {
        "away_team":"Wacker Innsbruck",
        "away_second_half_goals":0,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":1,
        "home_second_half_goals":1,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/zqnWtP5n-z3Zips56.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        9,
        8        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":3,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":2,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        8,
        18        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/6o19JD9K-O0THtLIa.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Liefering",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        16        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/2qC9lyTc-EZyzCyg4.png",
        "away_first_half_goals":0,
        "home_second_half_goals":1,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Ried",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        2,
        23        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien (Aut)",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/nJT3xoCK-0fAtQpUA.png",
        "away_first_half_goals":0,
        "home_second_half_goals":1,
        "home_match_goals":1,
        "league":"Club Friendly",
        "home_first_half_goals":0,
        "home_team":"Austria Vienna (Aut)",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(14,
        30        ),
        "date":datetime.date(2018,
        1,
        16        ),
        "country":"World"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/4AytPeA3-vLZTsIYf.png",
        "away_first_half_goals":1,
        "home_second_half_goals":0,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Hartberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        12,
        1        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/zqnWtP5n-z3Zips56.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":3,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Wacker Innsbruck",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        17        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":0,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/nBWIH1mh-6quCjKji.png",
        "away_first_half_goals":2,
        "home_second_half_goals":1,
        "home_match_goals":3,
        "league":"Erste Liga",
        "home_first_half_goals":2,
        "home_team":"Wattens",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        12        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":0,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/hnDiE7oh-hUxALml3.png",
        "away_first_half_goals":1,
        "home_second_half_goals":3,
        "home_match_goals":3,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"A. Lustenau",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        9        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":0,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/zqnWtP5n-z3Zips56.png",
        "away_first_half_goals":1,
        "home_second_half_goals":0,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Wacker Innsbruck",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        12,
        1        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/2qC9lyTc-EZyzCyg4.png",
        "away_first_half_goals":0,
        "home_second_half_goals":1,
        "home_match_goals":2,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Ried",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        17        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/A7qnAnUE-MsnoecZK.png",
        "away_first_half_goals":1,
        "home_second_half_goals":1,
        "home_match_goals":4,
        "league":"Erste Liga",
        "home_first_half_goals":3,
        "home_team":"Neustadt",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        10,
        20        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":2,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/IyIb4H7n-CWnHJbm6.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"BW Linz",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        9,
        29        ),
        "country":"Austria"
    },
    {
        "away_team":"BW Linz",
        "away_second_half_goals":2,
        "away_match_goals":4,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":2,
        "home_second_half_goals":1,
        "home_match_goals":1,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/IyIb4H7n-CWnHJbm6.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        20        ),
        "country":"Austria"
    },
    {
        "away_team":"Neustadt",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/A7qnAnUE-MsnoecZK.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2018,
        3,
        16        ),
        "country":"Austria"
    },
    {
        "away_team":"Liefering",
        "away_second_half_goals":4,
        "away_match_goals":5,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":1,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/6o19JD9K-O0THtLIa.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        24        ),
        "country":"Austria"
    },
    {
        "away_team":"Hartberg",
        "away_second_half_goals":1,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":1,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/4AytPeA3-vLZTsIYf.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        11,
        3        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":4,
        "league":"Erste Liga",
        "home_first_half_goals":2,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        10,
        31        ),
        "country":"Austria"
    },
    {
        "away_team":"A. Lustenau",
        "away_second_half_goals":0,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":1,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/hnDiE7oh-hUxALml3.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        10,
        13        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":4,
        "league":"Erste Liga",
        "home_first_half_goals":2,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        10,
        31        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":3,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":2,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2017,
        8,
        18        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":1,
        "home_match_goals":3,
        "league":"Erste Liga",
        "home_first_half_goals":2,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(19,
        30        ),
        "date":datetime.date(2017,
        5,
        26        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(16,
        0        ),
        "date":datetime.date(2017,
        4,
        8        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2016,
        11,
        18        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":0,
        "away_match_goals":0,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":2,
        "home_match_goals":2,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2016,
        9,
        13        ),
        "country":"Austria"
    },
    {
        "away_team":"FAC Wien",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "away_first_half_goals":0,
        "home_second_half_goals":3,
        "home_match_goals":4,
        "league":"Erste Liga",
        "home_first_half_goals":1,
        "home_team":"Kapfenberg",
        "away_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2016,
        5,
        10        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":1,
        "away_match_goals":1,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":0,
        "home_second_half_goals":0,
        "home_match_goals":0,
        "league":"Erste Liga",
        "home_first_half_goals":0,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(18,
        30        ),
        "date":datetime.date(2016,
        3,
        18        ),
        "country":"Austria"
    },
    {
        "away_team":"Kapfenberg",
        "away_second_half_goals":None,
        "away_match_goals":2,
        "home_logo_src":"http://i.sportstats.com/SY4Ud7Ot-QerFRpgR.png",
        "away_first_half_goals":None,
        "home_second_half_goals":None,
        "home_match_goals":1,
        "league":"OFB Cup",
        "home_first_half_goals":None,
        "home_team":"FAC Wien",
        "away_logo_src":"http://i.sportstats.com/CQfdaCiQ-phgpt3Fq.png",
        "time":datetime.time(19,
        0        ),
        "date":datetime.date(2010,
        8,
        13        ),
        "country":"Austria"
    }
]